### PR TITLE
<refactor> Add additional options to PR template

### PR DESCRIPTION
**Pull request by ml019**
## Description
- Add a refactor option as a type of change.
- Add a none of the above item to the checklist.

## Motivation and Context
As a significant number of the PRs generated fall into this category, it feels sensible to add this as an option. The alternative is to call them features which doesn't quite feel right.

The extra checklist item is to confirm that the submitter has reviewed the checklist but not found any relevant items.

## How Has This Been Tested?
Example in https://github.com/hamlet-io/executor-bash/pull/4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions
- [ ] create PR for engine
- [ ] create PR for engine-core
- [ ] create PR for engine-plugin-aws
- [ ] create PR for engine-plugin-azure
- [ ] create PR for executor-cookiecutter
- [ ] create PR for executor-bash
- [ ] create PR for executor-python
- [ ] create PR for cloudinit-aws

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ml019** [comment]
I'll create a PR for the other repos once we are happy with this one.

This PR also feels like it needs a "follow up actions" section where I could have said "Apply to other repos once changes agreed".

Thoughts?

**Comment by ml019** [comment]
@RossMurr4y @roleyfoley I've switched "Breaking Actions" to "Followup Actions" so it can be used for any followup from a change. Suggest a checklist which can then be updated as the actions are done or just a bullet list if we think it better to document but not capture progress.

**Comment by RossMurr4y** [comment]
@ml019 happy with Followup Actions.

A checklist would work best for plugins. Its quite frustrating when the "parent PR" in one of of the core repositories gets merged, and I've commented weeks back "please merge corresponding PR x when this is merged" and it gets missed because people dont re-read all the comments (understandable). At least if its in the root of the template people are more likely to recall that it's there and to check for it.

**Comment by ml019** [comment]
@RossMurr4y question was more where we just use ```-``` or ```- [x] ```. Either way we want people to look at it - but the checkbox means someone can edit it to say its done. However that still requires a manual update to a potentially merged PR

**Pull request merged**
